# Generated by Django 2.1.2 on 2018-11-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
