# Generated by Django 2.1.2 on 2018-11-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181111_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
